spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: test
    url: jdbc:mysql://localhost:3306
    username: root
    password: Clement1999


